// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbTbE-34AaI8JWhrOVsxIc4eJ6c1ViJdw',
    appId: '1:665799017824:web:e65d4247ea054075abca05',
    messagingSenderId: '665799017824',
    projectId: 'sharebite-mad-project',
    authDomain: 'sharebite-mad-project.firebaseapp.com',
    storageBucket: 'sharebite-mad-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0aEOvhgblRIV-Y4ADlQxM2ufcFsmH-84',
    appId: '1:665799017824:android:e23e46c6b8bcb866abca05',
    messagingSenderId: '665799017824',
    projectId: 'sharebite-mad-project',
    storageBucket: 'sharebite-mad-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfgS5tqX0-Sgney5L6pTlEJwc5SVxu2LQ',
    appId: '1:665799017824:ios:d7a1c856279a591aabca05',
    messagingSenderId: '665799017824',
    projectId: 'sharebite-mad-project',
    storageBucket: 'sharebite-mad-project.firebasestorage.app',
    iosBundleId: 'com.example.shareBite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfgS5tqX0-Sgney5L6pTlEJwc5SVxu2LQ',
    appId: '1:665799017824:ios:d7a1c856279a591aabca05',
    messagingSenderId: '665799017824',
    projectId: 'sharebite-mad-project',
    storageBucket: 'sharebite-mad-project.firebasestorage.app',
    iosBundleId: 'com.example.shareBite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbTbE-34AaI8JWhrOVsxIc4eJ6c1ViJdw',
    appId: '1:665799017824:web:31a5f636a7568fc7abca05',
    messagingSenderId: '665799017824',
    projectId: 'sharebite-mad-project',
    authDomain: 'sharebite-mad-project.firebaseapp.com',
    storageBucket: 'sharebite-mad-project.firebasestorage.app',
  );
}
